[package]
name = "test-client"
version = "0.2.1"
edition = "2021"

[[bin]]
name = "test-client"
path = "src/main.rs"

[dependencies]
mxp = "0.2.0"
serde_json.workspace = true
anyhow.workspace = true

[features]
debug-tools = []



